import React, { useState, useMemo } from "react";
import {
  AlertTriangle, Search, Filter, ChevronDown, X, Clock, Shield,
  Server, FileText, MessageSquare, CheckCircle2, CircleSlash,
  ChevronRight, ChevronLeft, MoreVertical, RefreshCw, ArrowUpRight,
  Activity, User, Tag, Hash
} from "lucide-react";
import {
  AreaChart, Area, ResponsiveContainer, Tooltip, XAxis
} from "recharts";

/* ------------------------------------------------------------------ */
/*  Design tokens (do not alter — inherited from existing app theme)   */
/* ------------------------------------------------------------------ */
const COLORS = {
  bg: "#0F1115",
  bgSecondary: "#171A1D",
  card: "#1C2026",
  border: "#2A2F36",
  text: "#FFFFFF",
  muted: "#A1A1AA", // zinc-400
  accent: "#22D3EE", // cyan
  success: "#34D399", // emerald
  warning: "#F59E0B", // amber
  danger: "#F87171", // red
};

/* ------------------------------------------------------------------ */
/*  Mock data                                                          */
/* ------------------------------------------------------------------ */
const SEVERITIES = ["critical", "high", "medium", "low"];
const STATUSES = ["open", "acknowledged", "resolved", "false_positive"];

const SEVERITY_META = {
  critical: { label: "Critical", color: COLORS.danger, ring: "rgba(248,113,113,0.15)" },
  high: { label: "High", color: "#FB923C", ring: "rgba(251,146,60,0.15)" },
  medium: { label: "Medium", color: COLORS.warning, ring: "rgba(245,158,11,0.15)" },
  low: { label: "Low", color: COLORS.accent, ring: "rgba(34,211,238,0.15)" },
};

const STATUS_META = {
  open: { label: "Open", color: COLORS.danger },
  acknowledged: { label: "Acknowledged", color: COLORS.warning },
  resolved: { label: "Resolved", color: COLORS.success },
  false_positive: { label: "False Positive", color: COLORS.muted },
};

function genTrend(seedBase) {
  return Array.from({ length: 12 }, (_, i) => ({
    t: i,
    v: Math.max(1, Math.round(seedBase + Math.sin(i / 2 + seedBase) * 4 + (i % 3))),
  }));
}

const RULE_NAMES = [
  "Multiple Failed Logins From Single Source",
  "Lateral Movement via SMB",
  "Suspicious PowerShell Execution",
  "Outbound Connection to Known C2",
  "Privilege Escalation Detected",
  "Unusual Data Exfiltration Volume",
  "Brute Force on VPN Gateway",
  "Malware Signature Match",
  "Anomalous Admin Account Activity",
  "DNS Tunneling Indicator",
];

const DEVICES = [
  { name: "WEB-PROD-04", ip: "10.12.4.18", type: "Server" },
  { name: "DC-CORP-01", ip: "10.0.0.5", type: "Domain Controller" },
  { name: "FIN-WS-221", ip: "10.20.6.91", type: "Workstation" },
  { name: "EDGE-FW-02", ip: "172.16.0.2", type: "Firewall" },
  { name: "HR-LAPTOP-77", ip: "10.20.9.45", type: "Laptop" },
  { name: "DB-CLUSTER-03", ip: "10.12.1.30", type: "Database" },
];

const ANALYSTS = ["Priya Nair", "Marcus Webb", "Elena Torres", "Sam Okafor", "Unassigned"];

function makeAlert(id) {
  const sev = SEVERITIES[Math.floor(Math.random() * 100) % SEVERITIES.length === 0 && id % 7 === 0 ? 0 : (id * 3) % SEVERITIES.length];
  const severity = SEVERITIES[(id * 7) % SEVERITIES.length];
  const status = STATUSES[(id * 5) % STATUSES.length];
  const device = DEVICES[id % DEVICES.length];
  const rule = RULE_NAMES[id % RULE_NAMES.length];
  const hoursAgo = (id * 37) % 96;
  const ts = new Date(Date.now() - hoursAgo * 3600 * 1000);
  return {
    id: `ALT-${String(1000 + id)}`,
    title: rule,
    severity,
    status,
    device,
    rule,
    analyst: status === "open" ? "Unassigned" : ANALYSTS[id % ANALYSTS.length],
    timestamp: ts,
    description:
      "Correlated event activity matched detection logic for this rule across multiple log sources within a 5-minute window, exceeding the configured threshold.",
    sourceIp: `${10 + (id % 50)}.${(id * 3) % 255}.${(id * 7) % 255}.${(id * 11) % 255}`,
    destIp: device.ip,
    mitre: ["T1110", "T1021", "T1059", "T1078", "T1041"][id % 5],
    rawLog: `<134>1 ${ts.toISOString()} ${device.name} sshd[2841]: Failed password for invalid user admin from ${10 + (id % 50)}.${(id * 3) % 255}.0.1 port 51422 ssh2`,
    timeline: [
      { t: "Detected", time: ts, detail: "Alert generated by correlation engine" },
      { t: "Triaged", time: new Date(ts.getTime() + 6 * 60000), detail: status !== "open" ? `Reviewed by ${ANALYSTS[id % ANALYSTS.length]}` : null },
      { t: "Escalated", time: new Date(ts.getTime() + 22 * 60000), detail: severity === "critical" ? "Escalated to incident response" : null },
    ].filter((x) => x.detail !== null),
    notes:
      status === "resolved"
        ? [{ author: ANALYSTS[id % ANALYSTS.length], text: "Confirmed benign — scheduled maintenance window. Closing.", time: new Date(ts.getTime() + 40 * 60000) }]
        : [],
    trend: genTrend((id % 5) + 2),
  };
}

const ALL_ALERTS = Array.from({ length: 47 }, (_, i) => makeAlert(i + 1));

/* ------------------------------------------------------------------ */
/*  Reusable primitives                                                */
/* ------------------------------------------------------------------ */
function SeverityBadge({ severity }) {
  const meta = SEVERITY_META[severity];
  return (
    <span
      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border"
      style={{ color: meta.color, background: meta.ring, borderColor: `${meta.color}33` }}
    >
      <span className="w-1.5 h-1.5 rounded-full" style={{ background: meta.color }} />
      {meta.label}
    </span>
  );
}

function StatusBadge({ status }) {
  const meta = STATUS_META[status];
  return (
    <span
      className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium border"
      style={{ color: meta.color, borderColor: COLORS.border, background: "rgba(255,255,255,0.02)" }}
    >
      {meta.label}
    </span>
  );
}

function timeAgo(date) {
  const diffMs = Date.now() - date.getTime();
  const mins = Math.floor(diffMs / 60000);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.floor(hrs / 24)}d ago`;
}

function MetricChip({ label, value, color }) {
  return (
    <div
      className="flex-1 min-w-[140px] rounded-2xl border p-4 transition-all duration-200 hover:border-opacity-60"
      style={{ background: COLORS.card, borderColor: COLORS.border }}
    >
      <div className="flex items-center justify-between mb-2">
        <span className="text-xs font-medium" style={{ color: COLORS.muted }}>{label}</span>
        <span className="w-2 h-2 rounded-full" style={{ background: color }} />
      </div>
      <div className="text-2xl font-semibold" style={{ color: COLORS.text }}>{value}</div>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Filter bar                                                         */
/* ------------------------------------------------------------------ */
function FilterDropdown({ label, options, value, onChange, icon: Icon }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="relative">
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex items-center gap-2 px-3.5 py-2 rounded-xl border text-sm transition-colors duration-150 hover:border-opacity-80"
        style={{
          borderColor: value !== "all" ? COLORS.accent + "55" : COLORS.border,
          background: value !== "all" ? "rgba(34,211,238,0.06)" : COLORS.bgSecondary,
          color: value !== "all" ? COLORS.accent : COLORS.text,
        }}
      >
        {Icon && <Icon size={14} />}
        <span>{label}: {value === "all" ? "All" : options.find((o) => o.value === value)?.label}</span>
        <ChevronDown size={14} style={{ color: COLORS.muted }} />
      </button>
      {open && (
        <>
          <div className="fixed inset-0 z-10" onClick={() => setOpen(false)} />
          <div
            className="absolute top-full mt-2 left-0 z-20 w-48 rounded-xl border shadow-2xl overflow-hidden animate-[fadeIn_0.15s_ease-out]"
            style={{ background: COLORS.card, borderColor: COLORS.border }}
          >
            <button
              onClick={() => { onChange("all"); setOpen(false); }}
              className="w-full text-left px-3.5 py-2.5 text-sm hover:bg-white/5 transition-colors"
              style={{ color: COLORS.muted }}
            >
              All
            </button>
            {options.map((o) => (
              <button
                key={o.value}
                onClick={() => { onChange(o.value); setOpen(false); }}
                className="w-full text-left px-3.5 py-2.5 text-sm hover:bg-white/5 transition-colors flex items-center gap-2"
                style={{ color: COLORS.text }}
              >
                {o.dot && <span className="w-1.5 h-1.5 rounded-full" style={{ background: o.dot }} />}
                {o.label}
              </button>
            ))}
          </div>
        </>
      )}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Alert detail drawer                                                */
/* ------------------------------------------------------------------ */
function AlertDetail({ alert, onClose, onUpdateStatus }) {
  const [note, setNote] = useState("");
  const [notes, setNotes] = useState(alert.notes);
  const sevMeta = SEVERITY_META[alert.severity];

  return (
    <div className="fixed inset-0 z-40 flex justify-end">
      <div
        className="absolute inset-0 bg-black/60 backdrop-blur-sm animate-[fadeIn_0.2s_ease-out]"
        onClick={onClose}
      />
      <div
        className="relative w-full max-w-2xl h-full overflow-y-auto border-l animate-[slideIn_0.25s_ease-out] flex flex-col"
        style={{ background: COLORS.bg, borderColor: COLORS.border }}
      >
        {/* Header */}
        <div
          className="sticky top-0 z-10 px-7 py-5 border-b backdrop-blur-xl"
          style={{ background: "rgba(15,17,21,0.92)", borderColor: COLORS.border }}
        >
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="text-xs font-mono" style={{ color: COLORS.muted }}>{alert.id}</span>
                <SeverityBadge severity={alert.severity} />
                <StatusBadge status={alert.status} />
              </div>
              <h2 className="text-xl font-semibold" style={{ color: COLORS.text }}>{alert.title}</h2>
              <p className="text-sm mt-1 flex items-center gap-1.5" style={{ color: COLORS.muted }}>
                <Clock size={13} /> Detected {timeAgo(alert.timestamp)} · {alert.timestamp.toLocaleString()}
              </p>
            </div>
            <button
              onClick={onClose}
              className="p-2 rounded-xl border transition-colors hover:bg-white/5 shrink-0"
              style={{ borderColor: COLORS.border }}
            >
              <X size={16} style={{ color: COLORS.muted }} />
            </button>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-2 mt-5">
            <button
              onClick={() => onUpdateStatus(alert.id, "acknowledged")}
              disabled={alert.status === "acknowledged"}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-sm font-medium border transition-all duration-150 disabled:opacity-40"
              style={{ borderColor: COLORS.warning + "44", color: COLORS.warning, background: "rgba(245,158,11,0.07)" }}
            >
              <CircleSlash size={14} /> Acknowledge
            </button>
            <button
              onClick={() => onUpdateStatus(alert.id, "resolved")}
              disabled={alert.status === "resolved"}
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-sm font-medium border transition-all duration-150 disabled:opacity-40"
              style={{ borderColor: COLORS.success + "44", color: COLORS.success, background: "rgba(52,211,153,0.07)" }}
            >
              <CheckCircle2 size={14} /> Resolve
            </button>
            <button
              className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl text-sm font-medium border transition-all duration-150 ml-auto hover:bg-white/5"
              style={{ borderColor: COLORS.border, color: COLORS.text }}
            >
              <ArrowUpRight size={14} /> Create Incident
            </button>
          </div>
        </div>

        {/* Body */}
        <div className="px-7 py-6 space-y-6 flex-1">
          {/* Description */}
          <section>
            <SectionLabel icon={FileText} text="Description" />
            <p className="text-sm leading-relaxed" style={{ color: COLORS.muted }}>{alert.description}</p>
          </section>

          {/* Key facts grid */}
          <section className="grid grid-cols-2 gap-3">
            <FactCard icon={Shield} label="Detection Rule" value={alert.rule} />
            <FactCard icon={Hash} label="MITRE ATT&CK" value={alert.mitre} />
            <FactCard icon={Server} label="Affected Device" value={`${alert.device.name}`} sub={alert.device.ip} />
            <FactCard icon={User} label="Assigned Analyst" value={alert.analyst} />
            <FactCard icon={Tag} label="Source IP" value={alert.sourceIp} />
            <FactCard icon={Tag} label="Destination IP" value={alert.destIp} />
          </section>

          {/* Trend */}
          <section>
            <SectionLabel icon={Activity} text="Related Activity (12h)" />
            <div
              className="rounded-2xl border p-4"
              style={{ background: COLORS.card, borderColor: COLORS.border }}
            >
              <ResponsiveContainer width="100%" height={80}>
                <AreaChart data={alert.trend}>
                  <defs>
                    <linearGradient id="detailTrend" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="0%" stopColor={sevMeta.color} stopOpacity={0.35} />
                      <stop offset="100%" stopColor={sevMeta.color} stopOpacity={0} />
                    </linearGradient>
                  </defs>
                  <XAxis dataKey="t" hide />
                  <Tooltip
                    contentStyle={{ background: COLORS.bgSecondary, border: `1px solid ${COLORS.border}`, borderRadius: 12, fontSize: 12 }}
                    labelStyle={{ display: "none" }}
                  />
                  <Area type="monotone" dataKey="v" stroke={sevMeta.color} strokeWidth={2} fill="url(#detailTrend)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </section>

          {/* Raw log */}
          <section>
            <SectionLabel icon={FileText} text="Raw Log" />
            <div
              className="rounded-2xl border p-4 font-mono text-xs overflow-x-auto"
              style={{ background: "#0B0D10", borderColor: COLORS.border, color: COLORS.accent }}
            >
              {alert.rawLog}
            </div>
          </section>

          {/* Timeline */}
          <section>
            <SectionLabel icon={Clock} text="Timeline" />
            <div className="space-y-0">
              {alert.timeline.map((step, i) => (
                <div key={i} className="flex gap-3">
                  <div className="flex flex-col items-center">
                    <span className="w-2.5 h-2.5 rounded-full mt-1.5" style={{ background: COLORS.accent }} />
                    {i < alert.timeline.length - 1 && (
                      <span className="w-px flex-1 my-1" style={{ background: COLORS.border }} />
                    )}
                  </div>
                  <div className="pb-5">
                    <div className="flex items-center gap-2">
                      <span className="text-sm font-medium" style={{ color: COLORS.text }}>{step.t}</span>
                      <span className="text-xs" style={{ color: COLORS.muted }}>{step.time.toLocaleTimeString()}</span>
                    </div>
                    <p className="text-xs mt-0.5" style={{ color: COLORS.muted }}>{step.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Analyst notes */}
          <section>
            <SectionLabel icon={MessageSquare} text="Analyst Notes" />
            <div className="space-y-3 mb-3">
              {notes.length === 0 && (
                <p className="text-sm" style={{ color: COLORS.muted }}>No notes yet. Add context for other analysts below.</p>
              )}
              {notes.map((n, i) => (
                <div key={i} className="rounded-xl border p-3" style={{ background: COLORS.card, borderColor: COLORS.border }}>
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-medium" style={{ color: COLORS.text }}>{n.author}</span>
                    <span className="text-xs" style={{ color: COLORS.muted }}>{timeAgo(n.time)}</span>
                  </div>
                  <p className="text-sm" style={{ color: COLORS.muted }}>{n.text}</p>
                </div>
              ))}
            </div>
            <div className="flex gap-2">
              <input
                value={note}
                onChange={(e) => setNote(e.target.value)}
                placeholder="Add a note for this alert..."
                className="flex-1 px-3.5 py-2.5 rounded-xl border text-sm outline-none transition-colors focus:border-cyan-400/50"
                style={{ background: COLORS.bgSecondary, borderColor: COLORS.border, color: COLORS.text }}
              />
              <button
                onClick={() => {
                  if (!note.trim()) return;
                  setNotes((prev) => [...prev, { author: "You", text: note, time: new Date() }]);
                  setNote("");
                }}
                className="px-4 py-2.5 rounded-xl text-sm font-medium transition-colors"
                style={{ background: COLORS.accent, color: "#0F1115" }}
              >
                Add Note
              </button>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}

function SectionLabel({ icon: Icon, text }) {
  return (
    <div className="flex items-center gap-2 mb-3">
      <Icon size={14} style={{ color: COLORS.accent }} />
      <h3 className="text-sm font-semibold" style={{ color: COLORS.text }}>{text}</h3>
    </div>
  );
}

function FactCard({ icon: Icon, label, value, sub }) {
  return (
    <div className="rounded-xl border p-3.5" style={{ background: COLORS.card, borderColor: COLORS.border }}>
      <div className="flex items-center gap-1.5 mb-1.5">
        <Icon size={12} style={{ color: COLORS.muted }} />
        <span className="text-xs" style={{ color: COLORS.muted }}>{label}</span>
      </div>
      <div className="text-sm font-medium truncate" style={{ color: COLORS.text }}>{value}</div>
      {sub && <div className="text-xs mt-0.5" style={{ color: COLORS.muted }}>{sub}</div>}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Empty / Loading / Error states                                     */
/* ------------------------------------------------------------------ */
function EmptyState({ onReset }) {
  return (
    <div className="flex flex-col items-center justify-center py-20 text-center">
      <div
        className="w-14 h-14 rounded-2xl border flex items-center justify-center mb-4"
        style={{ background: COLORS.card, borderColor: COLORS.border }}
      >
        <Search size={22} style={{ color: COLORS.muted }} />
      </div>
      <h3 className="text-base font-semibold mb-1" style={{ color: COLORS.text }}>No alerts match these filters</h3>
      <p className="text-sm mb-5" style={{ color: COLORS.muted }}>Try widening your search or clearing a filter.</p>
      <button
        onClick={onReset}
        className="px-4 py-2 rounded-xl text-sm font-medium border transition-colors hover:bg-white/5"
        style={{ borderColor: COLORS.border, color: COLORS.text }}
      >
        Clear filters
      </button>
    </div>
  );
}

function LoadingRows() {
  return (
    <div className="space-y-2 p-4">
      {Array.from({ length: 8 }).map((_, i) => (
        <div
          key={i}
          className="h-14 rounded-xl animate-pulse"
          style={{ background: COLORS.card, opacity: 1 - i * 0.05 }}
        />
      ))}
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  Main page                                                          */
/* ------------------------------------------------------------------ */
export default function AlertsPage() {
  const [alerts, setAlerts] = useState(ALL_ALERTS);
  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [selected, setSelected] = useState(null);
  const [page, setPage] = useState(1);
  const [loading, setLoading] = useState(false);
  const pageSize = 8;

  const filtered = useMemo(() => {
    return alerts.filter((a) => {
      if (severityFilter !== "all" && a.severity !== severityFilter) return false;
      if (statusFilter !== "all" && a.status !== statusFilter) return false;
      if (search && !`${a.title} ${a.id} ${a.device.name}`.toLowerCase().includes(search.toLowerCase())) return false;
      return true;
    });
  }, [alerts, severityFilter, statusFilter, search]);

  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const pageItems = filtered.slice((page - 1) * pageSize, page * pageSize);

  const counts = useMemo(() => {
    const c = { critical: 0, high: 0, medium: 0, low: 0, open: 0 };
    alerts.forEach((a) => {
      c[a.severity] = (c[a.severity] || 0) + 1;
      if (a.status === "open") c.open++;
    });
    return c;
  }, [alerts]);

  function handleUpdateStatus(id, status) {
    setAlerts((prev) => prev.map((a) => (a.id === id ? { ...a, status } : a)));
    setSelected((prev) => (prev ? { ...prev, status } : prev));
  }

  function handleRefresh() {
    setLoading(true);
    setTimeout(() => setLoading(false), 700);
  }

  return (
    <div className="min-h-screen w-full" style={{ background: COLORS.bg }}>
      <style>{`
        @keyframes fadeIn { from { opacity: 0 } to { opacity: 1 } }
        @keyframes slideIn { from { transform: translateX(24px); opacity: 0 } to { transform: translateX(0); opacity: 1 } }
      `}</style>

      <div className="max-w-[1400px] mx-auto px-8 py-8">
        {/* Page header */}
        <div className="flex items-start justify-between mb-7">
          <div>
            <div className="flex items-center gap-2.5">
              <div
                className="w-9 h-9 rounded-xl flex items-center justify-center border"
                style={{ background: "rgba(248,113,113,0.08)", borderColor: COLORS.danger + "33" }}
              >
                <AlertTriangle size={17} style={{ color: COLORS.danger }} />
              </div>
              <h1 className="text-2xl font-semibold" style={{ color: COLORS.text }}>Alerts</h1>
            </div>
            <p className="text-sm mt-2" style={{ color: COLORS.muted }}>
              {counts.open} open alerts requiring triage across your environment
            </p>
          </div>
          <button
            onClick={handleRefresh}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl border text-sm font-medium transition-colors hover:bg-white/5"
            style={{ borderColor: COLORS.border, color: COLORS.text }}
          >
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} /> Refresh
          </button>
        </div>

        {/* Metric chips */}
        <div className="flex flex-wrap gap-3 mb-6">
          <MetricChip label="Critical" value={counts.critical} color={SEVERITY_META.critical.color} />
          <MetricChip label="High" value={counts.high} color={SEVERITY_META.high.color} />
          <MetricChip label="Medium" value={counts.medium} color={SEVERITY_META.medium.color} />
          <MetricChip label="Low" value={counts.low} color={SEVERITY_META.low.color} />
          <MetricChip label="Open / Unresolved" value={counts.open} color={COLORS.accent} />
        </div>

        {/* Filter bar */}
        <div
          className="flex flex-wrap items-center gap-3 mb-5 p-4 rounded-2xl border"
          style={{ background: COLORS.bgSecondary, borderColor: COLORS.border }}
        >
          <div className="relative flex-1 min-w-[220px]">
            <Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2" style={{ color: COLORS.muted }} />
            <input
              value={search}
              onChange={(e) => { setSearch(e.target.value); setPage(1); }}
              placeholder="Search by title, ID, or device..."
              className="w-full pl-9 pr-3 py-2.5 rounded-xl border text-sm outline-none transition-colors"
              style={{ background: COLORS.bg, borderColor: COLORS.border, color: COLORS.text }}
            />
          </div>
          <FilterDropdown
            label="Severity"
            icon={Filter}
            value={severityFilter}
            onChange={(v) => { setSeverityFilter(v); setPage(1); }}
            options={SEVERITIES.map((s) => ({ value: s, label: SEVERITY_META[s].label, dot: SEVERITY_META[s].color }))}
          />
          <FilterDropdown
            label="Status"
            icon={Filter}
            value={statusFilter}
            onChange={(v) => { setStatusFilter(v); setPage(1); }}
            options={STATUSES.map((s) => ({ value: s, label: STATUS_META[s].label, dot: STATUS_META[s].color }))}
          />
          {(severityFilter !== "all" || statusFilter !== "all" || search) && (
            <button
              onClick={() => { setSeverityFilter("all"); setStatusFilter("all"); setSearch(""); setPage(1); }}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-sm transition-colors hover:bg-white/5"
              style={{ color: COLORS.muted }}
            >
              <X size={13} /> Clear
            </button>
          )}
        </div>

        {/* Table */}
        <div
          className="rounded-2xl border overflow-hidden"
          style={{ background: COLORS.card, borderColor: COLORS.border }}
        >
          {loading ? (
            <LoadingRows />
          ) : pageItems.length === 0 ? (
            <EmptyState onReset={() => { setSeverityFilter("all"); setStatusFilter("all"); setSearch(""); }} />
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr
                    className="text-left sticky top-0 z-10"
                    style={{ background: COLORS.bgSecondary }}
                  >
                    {["Alert", "Severity", "Status", "Device", "Analyst", "Detected", ""].map((h) => (
                      <th
                        key={h}
                        className="px-5 py-3.5 font-medium text-xs uppercase tracking-wide"
                        style={{ color: COLORS.muted, borderBottom: `1px solid ${COLORS.border}` }}
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {pageItems.map((a) => (
                    <tr
                      key={a.id}
                      onClick={() => setSelected(a)}
                      className="cursor-pointer transition-colors duration-150 hover:bg-white/[0.03]"
                      style={{ borderBottom: `1px solid ${COLORS.border}` }}
                    >
                      <td className="px-5 py-3.5">
                        <div className="font-medium" style={{ color: COLORS.text }}>{a.title}</div>
                        <div className="text-xs font-mono mt-0.5" style={{ color: COLORS.muted }}>{a.id}</div>
                      </td>
                      <td className="px-5 py-3.5"><SeverityBadge severity={a.severity} /></td>
                      <td className="px-5 py-3.5"><StatusBadge status={a.status} /></td>
                      <td className="px-5 py-3.5">
                        <div style={{ color: COLORS.text }}>{a.device.name}</div>
                        <div className="text-xs" style={{ color: COLORS.muted }}>{a.device.ip}</div>
                      </td>
                      <td className="px-5 py-3.5" style={{ color: a.analyst === "Unassigned" ? COLORS.muted : COLORS.text }}>
                        {a.analyst}
                      </td>
                      <td className="px-5 py-3.5" style={{ color: COLORS.muted }}>{timeAgo(a.timestamp)}</td>
                      <td className="px-5 py-3.5 text-right">
                        <ChevronRight size={15} style={{ color: COLORS.muted }} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

          {/* Pagination */}
          {!loading && pageItems.length > 0 && (
            <div
              className="flex items-center justify-between px-5 py-3.5 border-t"
              style={{ borderColor: COLORS.border }}
            >
              <span className="text-xs" style={{ color: COLORS.muted }}>
                Showing {(page - 1) * pageSize + 1}–{Math.min(page * pageSize, filtered.length)} of {filtered.length}
              </span>
              <div className="flex items-center gap-1.5">
                <button
                  onClick={() => setPage((p) => Math.max(1, p - 1))}
                  disabled={page === 1}
                  className="p-1.5 rounded-lg border transition-colors hover:bg-white/5 disabled:opacity-30"
                  style={{ borderColor: COLORS.border }}
                >
                  <ChevronLeft size={14} style={{ color: COLORS.text }} />
                </button>
                <span className="text-xs px-2" style={{ color: COLORS.muted }}>{page} / {totalPages}</span>
                <button
                  onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  disabled={page === totalPages}
                  className="p-1.5 rounded-lg border transition-colors hover:bg-white/5 disabled:opacity-30"
                  style={{ borderColor: COLORS.border }}
                >
                  <ChevronRight size={14} style={{ color: COLORS.text }} />
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {selected && (
        <AlertDetail
          alert={selected}
          onClose={() => setSelected(null)}
          onUpdateStatus={handleUpdateStatus}
        />
      )}
    </div>
  );
}